[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python -c 'import sys; print(f\"Python {sys.version}\")'",
    "python -c 'import fastapi; print(f\"FastAPI {fastapi.__version__}\")'"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
