version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./jamanager.db
      - JAM_MANAGER_ACCESS_CODE=jam2024
    volumes:
      - .:/app
      - ./static:/app/static
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
